[package]
name = "moneter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
material-colors = "0.1.1"

[profile.release]
opt-level = 3
